name: Release app

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          - name: Linux amd64
            image: ubuntu-24.04
          - name: Linux arm64
            image: ubuntu-24.04-arm
          - name: macOS
            image: macos-latest
          - name: Windows
            image: windows-latest
    runs-on: ${{ matrix.os.image }}
    name: Build (${{ matrix.os.name }})
    permissions:
      contents: write

    steps:
      - name: Github checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci --include=dev

      - name: Extract codesigning certificate
        if: matrix.os.name == 'macOS'
        run: |
          echo "${{ secrets.CODESIGN_CERTIFICATE_B64 }}" | base64 -d > certificate.p12
          security create-keychain -p "${{ secrets.KEYCHAIN_PASSWORD }}" build.keychain
          security set-keychain-settings -lut 21600 build.keychain
          security unlock-keychain -p "${{ secrets.KEYCHAIN_PASSWORD }}" build.keychain
          security import certificate.p12 -k build.keychain -A -P "${{ secrets.CODESIGN_CERTIFICATE_PASSWORD }}"
          rm certificate.p12
          security set-key-partition-list -S apple-tool:,apple: -s -k "${{ secrets.KEYCHAIN_PASSWORD }}" build.keychain
          security list-keychains -s build.keychain
          security default-keychain -s build.keychain
          echo "${{ secrets.APPLE_API_KEY }}" | base64 -d > apple_api_key.p8
          echo APPLE_API_KEY_PATH=apple_api_key.p8 >> $GITHUB_ENV
          echo APPLE_API_KEY_ID=${{ secrets.APPLE_API_KEY_ID }} >> $GITHUB_ENV
          echo APPLE_API_ISSUER=${{ secrets.APPLE_API_ISSUER }} >> $GITHUB_ENV

      - name: Publish app
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
