name: Release app

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          - name: Linux
            image: ubuntu-latest
          - name: macOS
            image: macos-latest
          - name: Windows
            image: windows-latest
    runs-on: ${{ matrix.os.image }}
    name: Build (${{ matrix.os.name }})

    steps:
      - name: Github checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci

      - name: Publish app
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
